"use strict";
const API="https://undefined-seeks-mall-disclose.trycloudflare.com";
const TOKEN_KEY="khanh-course-student-session";
const state={token:sessionStorage.getItem(TOKEN_KEY)||"",weeks:[],submissions:[]};
const $=selector=>document.querySelector(selector);

function setStatus(element,message,type=""){element.textContent=message;element.className=`status ${type}`.trim()}
function make(tag,text,className=""){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(className)node.className=className;return node}
async function api(path,options={}){const headers={...(options.body?{"Content-Type":"application/json"}:{}),...(state.token?{Authorization:`Bearer ${state.token}`}:{})};const response=await fetch(API+path,{...options,headers:{...headers,...options.headers}});let data={};try{data=await response.json()}catch(_){data={}}if(!response.ok){const error=new Error(data.error||"request_failed");error.status=response.status;throw error}return data}
function statusLabel(value){return {SUBMITTED:"Đã nộp",NEEDS_REVISION:"Cần sửa",PASSED:"Đạt"}[value]||"Chưa nộp"}
function latestForWeek(week){return state.submissions.filter(x=>x.week===week).sort((a,b)=>b.version-a.version)[0]}
function renderWeeks(){const list=$("#week-list");list.replaceChildren();state.weeks.forEach(week=>{const latest=latestForWeek(week.week);const card=make("article",undefined,"week-card");card.append(make("p",`TUẦN ${String(week.week).padStart(2,"0")}`,"week-number"),make("h3",week.title),make("p",week.artifact));const badge=make("span",statusLabel(latest?.review_status),`badge ${(latest?.review_status||"").toLowerCase().replace("_","-")}`);card.append(badge);const button=make("button",latest?"Nộp phiên bản mới":"Nộp sản phẩm");button.type="button";button.addEventListener("click",()=>selectWeek(week));card.append(button);list.append(card)})}
function selectWeek(week){const form=$("#submission-form");form.hidden=false;$("#submission-empty").hidden=true;form.elements.week.value=String(week.week);$("#selected-week-label").textContent=`TUẦN ${String(week.week).padStart(2,"0")}`;$("#selected-week-title").textContent=week.title;$("#selected-week-artifact").textContent=week.artifact;form.scrollIntoView({behavior:"smooth",block:"start"});form.elements.artifact_url.focus()}
function renderHistory(){const list=$("#submission-history");list.replaceChildren();if(!state.submissions.length){list.append(make("p","Chưa có bài nộp. Chọn một tuần để gửi sản phẩm đầu tiên.","empty"));return}state.submissions.forEach(item=>{const card=make("article",undefined,"history-card");const meta=make("div");meta.append(make("strong",`Tuần ${item.week}`),make("p",`Phiên bản ${item.version}`));const body=make("div");const link=make("a","Mở sản phẩm");link.href=item.artifact_url;link.target="_blank";link.rel="noopener noreferrer";body.append(link,make("p",item.note));if(item.instructor_feedback){const feedback=make("div",undefined,"feedback");feedback.append(make("strong",`Phản hồi · ${item.instructor_score}/100`),make("p",item.instructor_feedback));body.append(feedback)}const badge=make("span",statusLabel(item.review_status),`badge ${item.review_status.toLowerCase().replace("_","-")}`);card.append(meta,body,badge);list.append(card)})}
async function loadApp(){const [weeks,profile,history]=await Promise.all([api("/course/portal/weeks"),api("/course/portal/me"),api("/course/portal/submissions")]);state.weeks=weeks.weeks;state.submissions=history.submissions;$("#student-name").textContent=profile.student.display_name;$("#student-cohort").textContent=`Cohort ${profile.student.cohort}`;$("#login-panel").hidden=true;$("#student-app").hidden=false;renderWeeks();renderHistory()}
$("#student-login").addEventListener("submit",async event=>{event.preventDefault();const status=$("#login-status");setStatus(status,"Đang xác thực…");const form=event.currentTarget;try{const result=await api("/course/portal/login",{method:"POST",body:JSON.stringify({application_id:form.elements.application_id.value.trim(),phone:form.elements.phone.value.trim()})});state.token=result.token;sessionStorage.setItem(TOKEN_KEY,state.token);await loadApp();setStatus(status,"")}catch(error){setStatus(status,error.status===401?"Mã hồ sơ hoặc số điện thoại không đúng.":"Chưa thể kết nối. Vui lòng thử lại.","error")}});
$("#submission-form").addEventListener("submit",async event=>{event.preventDefault();const form=event.currentTarget;const status=$("#submission-status");setStatus(status,"Đang lưu phiên bản…");const scores={};["completeness","quality","safety","repeatability"].forEach(key=>scores[key]=Number(form.elements[`self_${key}`].value));try{await api("/course/portal/submissions",{method:"POST",body:JSON.stringify({week:Number(form.elements.week.value),artifact_url:form.elements.artifact_url.value.trim(),note:form.elements.note.value.trim(),self_scores:scores})});const history=await api("/course/portal/submissions");state.submissions=history.submissions;renderWeeks();renderHistory();form.reset();form.hidden=true;$("#submission-empty").hidden=false;setStatus(status,"Đã lưu bài nộp.","success")}catch(_){setStatus(status,"Không thể lưu. Kiểm tra link HTTPS và các trường bắt buộc.","error")}});
document.querySelectorAll('input[type="range"]').forEach(input=>input.addEventListener("input",()=>{document.querySelector(`[data-score="${input.name.replace("self_","")}"]`).textContent=`${input.value}/4`}));
$("#logout").addEventListener("click",()=>{sessionStorage.removeItem(TOKEN_KEY);state.token="";location.reload()});
if(state.token)loadApp().catch(()=>{sessionStorage.removeItem(TOKEN_KEY);state.token=""});
