import {env} from 'cloudflare:workers';
export const COOKIE='__Host-design-admin';
export const SESSION_SECONDS=8*60*60;
const enc=new TextEncoder();
const config=()=>env as unknown as {ADMIN_PASSWORD_HASH?:string;ADMIN_SESSION_SECRET?:string};
const hex=(bytes:ArrayBuffer)=>Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,'0')).join('');
function bytes(s:string){if(!/^[a-f0-9]+$/.test(s)||s.length%2)throw Error('Invalid hex');return new Uint8Array(s.match(/../g)!.map(x=>parseInt(x,16)));}
export async function verifyPassword(password:string){const stored=config().ADMIN_PASSWORD_HASH;if(!stored)return false;const [rounds,salt,expected]=stored.split(':');if(!rounds||!salt||!expected)return false;const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const hash=hex(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:bytes(salt),iterations:Number(rounds)},key,256));let diff=hash.length^expected.length;for(let i=0;i<hash.length;i++)diff|=hash.charCodeAt(i)^(expected.charCodeAt(i)||0);return diff===0;}
async function signingKey(){const secret=config().ADMIN_SESSION_SECRET;if(!secret||secret.length<32)throw Error('Login is not configured');return crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign','verify']);}
export async function createSession(){const payload=btoa(JSON.stringify({sub:'admin',exp:Math.floor(Date.now()/1000)+SESSION_SECONDS,nonce:crypto.randomUUID()})).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');return payload+'.'+hex(await crypto.subtle.sign('HMAC',await signingKey(),enc.encode(payload)));}
export async function validSession(cookieHeader:string|null){try{const token=(cookieHeader||'').split(';').map(s=>s.trim()).find(s=>s.startsWith(COOKIE+'='))?.slice(COOKIE.length+1);if(!token||token.length>1024)return false;const parts=token.split('.');if(parts.length!==2)return false;const [payload,sig]=parts;if(!await crypto.subtle.verify('HMAC',await signingKey(),bytes(sig),enc.encode(payload)))return false;const claims=JSON.parse(atob(payload.replace(/-/g,'+').replace(/_/g,'/')));const now=Math.floor(Date.now()/1000);return claims.sub==='admin'&&Number.isInteger(claims.exp)&&claims.exp>now&&claims.exp<=now+SESSION_SECONDS;}catch{return false;}}
export function sessionCookie(value:string,age=SESSION_SECONDS){return `${COOKIE}=${value}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${age}`;}
