'use client';
import {useState,useEffect} from 'react';
import {ArrowLeft,ArrowRight,Printer,Maximize,FileText,ExternalLink} from 'lucide-react';
import {Project,attachments,statuses,Attachment,groupCode,itemCode} from './model';
export default function Report({project,onOpen}:{project:Project;onOpen:(f:Attachment)=>void}){
 const [index,setIndex]=useState(0);const items=project.groups.flatMap(g=>g.items);const total=project.groups.length+3;const current=Math.min(index,total-1);const [full,setFull]=useState(false);
 useEffect(()=>{if(!full)return;const handler=(e:KeyboardEvent)=>{if(e.key==='Escape')setFull(false);if(e.key==='ArrowRight')setIndex(i=>Math.min(total-1,i+1));if(e.key==='ArrowLeft')setIndex(i=>Math.max(0,i-1));};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[full,total]);
 const slide=(n:number)=><section key={n} className={'report-slide '+(n===current?'current':'')}>
 <div className="slide-top"><span>khanh.design</span><span>BÁO CÁO THIẾT KẾ / {String(n+1).padStart(2,'0')}</span></div>
 {n===0?<div className={'cover-layout '+(project.cover?'has-cover':'')}><div><span className="eyebrow">BỘ NHẬN DIỆN THƯƠNG HIỆU</span><h2>{project.name}</h2><p>{project.subtitle}</p><div className="cover-meta">{project.groups.length} nhóm thiết kế <span>·</span> {items.length} hạng mục</div></div>{project.cover&&<img src={project.cover} alt="Bìa dự án"/>}</div>:
 n===1?<><h2>Mục lục</h2><div className="contents-list"><button onClick={()=>setIndex(2)}><span>01</span><strong>Tổng quan tiến độ</strong><span>03</span></button>{project.groups.map((g,i)=><button key={g.id} onClick={()=>setIndex(i+3)}><span>{String(i+2).padStart(2,'0')}</span><strong>{g.name}</strong><span>{String(i+4).padStart(2,'0')}</span></button>)}</div></>:
 n===2?<><h2>Tổng quan dự án</h2><div className="report-stats">{statuses.map(s=><div key={s}><strong>{items.filter(i=>i.status===s).length}</strong><span className={'status s'+statuses.indexOf(s)}><i/>{s}</span></div>)}</div><div className="group-progress">{project.groups.map(g=>{const done=g.items.filter(i=>i.status==='Hoàn thành').length;return <div key={g.id}><span>{g.name}</span><div><i style={{width:`${g.items.length?done/g.items.length*100:0}%`}}/></div><strong>{done}/{g.items.length}</strong></div>})}</div></>:
 (()=>{const g=project.groups[n-3];if(!g)return null;const files=g.items.flatMap(attachments);return <><h2>{groupCode(n-3)} · {g.name}</h2><div className="group-report"><div className="report-task-list">{g.items.map((i,ii)=><div key={i.id}><strong>{itemCode(n-3,ii)} · {i.name}</strong><span className={'status s'+statuses.indexOf(i.status)}><i/>{i.status}</span>{i.note&&<p>{i.note}</p>}</div>)}{!g.items.length&&<p>Chưa có hạng mục trong nhóm.</p>}</div><div className="report-gallery">{files.slice(0,4).map(f=><button key={f.id} onClick={()=>onOpen(f)}>{f.type==='image'?<img src={f.url} alt={f.name}/>:<><FileText size={30}/><span>{f.name}</span><small>{f.type==='pdf'?'Mở PDF':'Mở Google Drive'} <ExternalLink size={12}/></small></>}</button>)}{!files.length&&<div className="report-no-files"><FileText size={30}/><p>Chưa có thiết kế đính kèm</p></div>}{files.length>4&&<span className="hint">+ {files.length-4} tệp khác trong Showcase</span>}</div></div></>})()}
 <div className="slide-bottom"><span>{project.name}</span><span>{String(n+1).padStart(2,'0')} / {String(total).padStart(2,'0')}</span></div></section>;
 return <div className={'report-area '+(full?'presenting':'')}><div className="report-toolbar"><div><strong>Slide tổng</strong><span>Bìa · Mục lục · Tiến độ · Thiết kế</span></div><div><button className="outline" onClick={()=>window.print()}><Printer size={16}/> In / Lưu PDF</button><button className="outline" onClick={()=>setFull(!full)}><Maximize size={16}/>{full?'Thoát trình chiếu':'Trình chiếu'}</button></div></div><div className="report-stage">{Array.from({length:total},(_,n)=>slide(n))}</div><div className="slide-navigation"><button className="outline" onClick={()=>setIndex(Math.max(0,current-1))} disabled={current===0}><ArrowLeft size={16}/> Trước</button><span>{current+1} / {total}</span><button className="outline" onClick={()=>setIndex(Math.min(total-1,current+1))} disabled={current===total-1}>Tiếp <ArrowRight size={16}/></button></div></div>
}
