'use client';
import {useEffect,useState,useRef} from 'react';
import {Download,Sun,Moon,LogIn,LogOut,Search,Plus,Network,LayoutGrid,Images,ArrowUpRight,Minus,Maximize,ChevronRight,ChevronDown,Upload,Trash2,Check,Loader2,Folder,GripVertical,MoreHorizontal,ArrowUp,ArrowDown,Undo2,FileText,ExternalLink,Presentation,Settings2,Link2,X} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {DropdownMenu,DropdownMenuContent,DropdownMenuItem,DropdownMenuTrigger} from '@/components/ui/dropdown-menu';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Progress} from '@/components/ui/progress';
import {Data,Item,Project,Attachment,DragNode,initial,statuses,attachments,moveNode,driveValid,groupCode,itemCode,groupLabel,layoutHierarchy} from './model';
import Report from './report';
import Showcase from './showcase';
import ShowcaseSlideshow,{type ShowcaseSlide} from './showcase-slideshow';
import {useMapNavigation} from './use-map-navigation';
function Picker({value,onChange,options,disabled=false}:{value:string;onChange:(v:string)=>void;options:(string|{value:string;label:string})[];disabled?:boolean}){return <Select value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger className="picker"><SelectValue/></SelectTrigger><SelectContent>{options.map(s=>typeof s==='string'?<SelectItem key={s} value={s}>{statuses.includes(s)?<Badge status={s}/>:s}</SelectItem>:<SelectItem key={s.value} value={s.value}>{s.label}</SelectItem>)}</SelectContent></Select>}
function Badge({status}:{status:string}){return <span className={'status s'+statuses.indexOf(status)}><i/>{status}</span>}
function Thumb({file}:{file?:Attachment}){return file?.type==='image'?<img src={file.url} alt=""/>:file?.type==='pdf'?<FileText size={21}/>:file?.type==='drive'?<Link2 size={21}/>:<Images size={19}/>}
type FormState={category?:string;renameOnly?:boolean;kind:'project'|'category'|'group'|'item';id?:string;group?:string;name:string;subtitle:string;driveFolder:string;cover:string};
export default function Workspace({isAdmin,token}:{isAdmin:boolean;token?:string}){
 const [itemPresentation,setItemPresentation]=useState<{slides:ShowcaseSlide[];start:number;trigger:HTMLElement}|null>(null);
 const [loginOpen,setLoginOpen]=useState(false),[loginBusy,setLoginBusy]=useState(false),[loginError,setLoginError]=useState(''),[username,setUsername]=useState('admin'),[password,setPassword]=useState('');
 async function login(e:React.FormEvent){e.preventDefault();setLoginBusy(true);setLoginError('');try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});const j=await r.json();if(!r.ok)throw Error(j.error);setPassword('');window.location.assign('/admin');}catch(e){setLoginError((e as Error).message)}finally{setLoginBusy(false)}}
 async function logout(){try{const r=await fetch('/api/auth/logout',{method:'POST'});if(!r.ok)throw Error();window.location.assign('/admin');}catch{setError('Chưa đăng xuất được. Vui lòng thử lại.')}}
 const [theme,setTheme]=useState(()=>typeof document==='undefined'?'light':document.documentElement.dataset.theme||'light');function toggleTheme(){const next=theme==='dark'?'light':'dark';setTheme(next);document.documentElement.dataset.theme=next;try{localStorage.setItem('design-theme',next)}catch{}}
 const [data,setData]=useState<Data>(initial),[revision,setRevision]=useState(0),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[projectId,setProject]=useState('khesanh'),[view,setView]=useState('map'),[search,setSearch]=useState(''),[filter,setFilter]=useState('Tất cả trạng thái'),[collapsed,setCollapsed]=useState<string[]>([]);
 const [edit,setEdit]=useState<{group:string;originalGroup:string;item:Item}|null>(null),[form,setForm]=useState<FormState|null>(null),[deleting,setDeleting]=useState<{kind:'project'|'group'|'item';id:string;group?:string;name:string}|null>(null),[uploading,setUploading]=useState(false),[preview,setPreview]=useState<Attachment|null>(null),[undo,setUndo]=useState<Data|null>(null),[retry,setRetry]=useState<Data|null>(null),[dropTarget,setDropTarget]=useState(''),[dragging,setDragging]=useState(false),[linkName,setLinkName]=useState(''),[linkUrl,setLinkUrl]=useState(''),[shareOpen,setShareOpen]=useState(false),[shareToken,setShareToken]=useState(''),[copied,setCopied]=useState(false);
 const {viewport,zoom,zoomIn,zoomOut,fit}=useMapNavigation(view==='map'&&loaded&&data.projects.length>0);const lock=useRef(false),drag=useRef<DragNode|null>(null),editRef=useRef<{group:string;originalGroup:string;item:Item}|null>(null),saveTimer=useRef<number|null>(null);const [savingEdit,setSavingEdit]=useState(false);useEffect(()=>{editRef.current=edit},[edit]);
 const project=data.projects.find(p=>p.id===projectId)||data.projects[0];const all=project?.groups.flatMap(g=>g.items)||[];const done=all.filter(i=>i.status==='Hoàn thành').length;const codeOf=new Map<string,string>(),groupCodeOf=new Map<string,string>();project?.groups.forEach((g,gi)=>{groupCodeOf.set(g.id,groupCode(gi));g.items.forEach((i,ii)=>codeOf.set(i.id,itemCode(gi,ii)));});
 async function load(){setError('');try{const r=await fetch(token?'/api/project/'+token:'/api/workspace');const j=await r.json();if(!r.ok)throw Error(j.error);setData(token?{projects:[j.data]}:j.data);setRevision(j.revision||0);if(token)setProject(j.data.id);setLoaded(true);}catch(e){setError((e as Error).message)}}
 useEffect(()=>{const timer=window.setTimeout(()=>{void load()},0);return()=>window.clearTimeout(timer)},[]);
 async function save(next:Data,remember=true){if(!isAdmin||lock.current||!loaded)return false;lock.current=true;setBusy(true);setError('');try{const r=await fetch('/api/workspace',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:next,revision})});const j=await r.json();if(!r.ok)throw Error(j.error);if(remember)setUndo(data);setData(next);setRevision(j.revision);setRetry(null);return true;}catch(e){setError((e as Error).message);setRetry(next);return false;}finally{lock.current=false;setBusy(false)}}
 function create(kind:FormState['kind'],group?:string){if(!isAdmin)return;setError('');setForm({kind,group,name:'',subtitle:'',driveFolder:'',cover:''})}
 function configure(){if(!isAdmin)return;setError('');setForm({kind:'project',id:project.id,name:project.name,subtitle:project.subtitle,driveFolder:project.driveFolder||'',cover:project.cover||''})}
 const shareUrl=()=>((typeof window!=='undefined'?window.location.origin:'')+'/p/'+shareToken);
 async function openShare(){if(!isAdmin||!project)return;let tk=project.shareToken;if(!tk){tk=crypto.randomUUID();const next=structuredClone(data);next.projects.find(p=>p.id===project.id)!.shareToken=tk;if(!await save(next,false))return}setShareToken(tk);setCopied(false);setShareOpen(true)}
 async function unshare(){const next=structuredClone(data);const p=next.projects.find(p=>p.id===project.id);if(p)delete p.shareToken;if(await save(next,false))setShareOpen(false)}
 function copyShare(){if(!shareToken)return;try{navigator.clipboard?.writeText(shareUrl()).then(()=>{setCopied(true);setTimeout(()=>setCopied(false),1500)}).catch(()=>{})}catch{}}
 async function submitForm(){if(!form?.name.trim()||!driveValid(form.driveFolder))return;const next=structuredClone(data),p=next.projects.find(p=>p.id===project?.id);const id=form.id||crypto.randomUUID();if(form.kind==='project'){const fields={name:form.name.trim(),subtitle:form.subtitle||'Dự án thiết kế',driveFolder:form.driveFolder,cover:form.cover};if(form.id)Object.assign(next.projects.find(p=>p.id===form.id)!,fields);else next.projects.push({id,...fields,groups:[]});}else if(form.kind==='category'){p!.groups.filter(g=>g.category===form.category).forEach(g=>{g.category=form.name.trim()});}else if(form.kind==='group'){const fields={name:form.name.trim(),category:form.category?.trim()||undefined};if(form.id)Object.assign(p!.groups.find(g=>g.id===form.id)!,fields);else p!.groups.push({id,...fields,items:[]});}else p!.groups.find(g=>g.id===form.group)!.items.push({id,name:form.name.trim(),status:statuses[0],note:'',images:[]});if(await save(next)){if(form.kind==='project')setProject(id);setForm(null)}}
 function open(group:string,item:Item){setError('');setLinkName('');setLinkUrl('');setEdit({group,originalGroup:group,item:structuredClone(item)})}
 function patchEdit(patch:Partial<Item>,delay=700){setEdit(prev=>prev?{...prev,item:{...prev.item,...patch}}:prev);scheduleEditSave(delay)}
function changeGroup(group:string){setEdit(prev=>prev?{...prev,group}:prev);scheduleEditSave(700)}
function buildEditedItem(next:Data,e:{group:string;originalGroup:string;item:Item}){const p=next.projects.find(p=>p.id===project.id);if(!p)return;const src=p.groups.find(g=>g.id===e.originalGroup);if(e.group===e.originalGroup){if(src)src.items=src.items.map(i=>i.id===e.item.id?e.item:i)}else{if(src)src.items=src.items.filter(i=>i.id!==e.item.id);const dst=p.groups.find(g=>g.id===e.group);(dst||src)?.items.push(e.item)}}
async function flushEditSave(){const e=editRef.current;if(!e||!e.item.name.trim()||!driveValid(e.item.driveUrl||'')){setSavingEdit(false);return}if(lock.current||busy){saveTimer.current=window.setTimeout(flushEditSave,450);return}const next=structuredClone(data);buildEditedItem(next,e);const ok=await save(next,false);if(ok)setEdit(prev=>prev?{...prev,originalGroup:e.group}:prev);setSavingEdit(false)}
function scheduleEditSave(delay=700){setSavingEdit(true);if(saveTimer.current)window.clearTimeout(saveTimer.current);saveTimer.current=window.setTimeout(flushEditSave,delay)}
function closeEdit(){void flushEditSave();setEdit(null)}
 async function remove(){if(!deleting)return;const next=structuredClone(data),p=next.projects.find(p=>p.id===project?.id);if(deleting.kind==='project')next.projects=next.projects.filter(p=>p.id!==deleting.id);if(deleting.kind==='group')p!.groups=p!.groups.filter(g=>g.id!==deleting.id);if(deleting.kind==='item'){const g=p!.groups.find(g=>g.id===deleting.group)!;g.items=g.items.filter(i=>i.id!==deleting.id)}if(await save(next)){setDeleting(null);setEdit(null)}}
 async function uploadFiles(files:FileList|File[],cover=false){const list=Array.from(files);if(!list.length)return;if(!cover&&edit){const remaining=20-attachments(edit.item).length;if(list.length>remaining){setError(`Tối đa 20 tệp mỗi hạng mục (còn ${remaining} chỗ).`);return}}setUploading(true);setError('');const added:Attachment[]=[];const failed:string[]=[];for(const file of list){if(cover&&!file.type.startsWith('image/')){failed.push(`${file.name}: cần tệp ảnh`);continue}try{const body=new FormData();body.append('file',file);const r=await fetch('/api/upload',{method:'POST',body});const j=await r.json();if(!r.ok)throw Error(j.error);added.push(j)}catch(e){failed.push(`${file.name}: ${(e as Error).message}`)}}if(cover&&added.length)setForm(prev=>prev?{...prev,cover:added[0].url}:prev);else if(added.length){setEdit(prev=>prev?{...prev,item:{...prev.item,files:[...(prev.item.files||[]),...added]}}:prev);scheduleEditSave(150)}if(failed.length)setError(failed.slice(0,3).join(' · '));setUploading(false)}
 function openItemFile(f:Attachment,trigger:HTMLElement){
  if(f.type!=='image'||!edit){openFile(f);return}
  const slides=attachments(edit.item).filter(file=>file.type==='image').map((file,imageIndex)=>({file,title:edit.item.name,itemId:edit.item.id,imageIndex}));
  const start=slides.findIndex(s=>s.file.id===f.id&&s.file.url===f.url);
  if(start>=0)setItemPresentation({slides,start,trigger});
 }
 function openFile(f:Attachment){if(f.type==='drive'){if(driveValid(f.url))window.open(f.url,'_blank','noopener,noreferrer')}else setPreview(f)}
 function removeFile(f:Attachment){setEdit(prev=>prev?{...prev,item:{...prev.item,images:prev.item.images.filter(x=>x!==f.url),files:(prev.item.files||[]).filter(x=>x.id!==f.id)}}:prev);scheduleEditSave(150)}
 function addLink(){if(!edit||!linkUrl.trim()||!driveValid(linkUrl.trim()))return;setEdit({...edit,item:{...edit.item,files:[...(edit.item.files||[]),{id:crypto.randomUUID(),name:linkName.trim()||'Tệp Google Drive',url:linkUrl.trim(),type:'drive'}]}});setLinkName('');setLinkUrl('');scheduleEditSave(150)}
 function targetAt(x:number,y:number){const el=document.elementFromPoint(x,y)?.closest('[data-drop]') as HTMLElement|null;try{return el?.dataset.drop?JSON.parse(el.dataset.drop) as DragNode:null}catch{return null}}
 function grip(node:DragNode){if(!isAdmin)return null;return <button className="grip" disabled={busy} aria-label="Kéo để sắp xếp; dùng menu để di chuyển bằng bàn phím" onPointerDown={e=>{e.stopPropagation();drag.current=node;setDragging(true);e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(!drag.current)return;e.stopPropagation();const t=targetAt(e.clientX,e.clientY);setDropTarget(t?.id||'');const v=viewport.current;if(v){const r=v.getBoundingClientRect();if(e.clientY>r.bottom-50)v.scrollTop+=14;if(e.clientY<r.top+50)v.scrollTop-=14;if(e.clientX>r.right-50)v.scrollLeft+=14;if(e.clientX<r.left+50)v.scrollLeft-=14}}} onPointerUp={e=>{e.stopPropagation();const from=drag.current,to=targetAt(e.clientX,e.clientY);drag.current=null;setDragging(false);setDropTarget('');if(from&&to){const next=moveNode(data,project.id,from,to);if(next!==data)save(next)}}} onPointerCancel={()=>{drag.current=null;setDragging(false);setDropTarget('')}}><GripVertical size={16}/></button>}
 function nudge(kind:'group'|'item',id:string,group:string|undefined,delta:number){if(kind==='group'){const at=project.groups.findIndex(g=>g.id===id),target=project.groups[at+delta];if(target)save(moveNode(data,project.id,{kind,id},{kind,id:target.id}));return;}const next=structuredClone(data),p=next.projects.find(p=>p.id===project.id)!;const list=p.groups.find(g=>g.id===group)!.items;const a=list.findIndex(i=>i.id===id),b=a+delta;if(b<0||b>=list.length)return;[list[a],list[b]]=[list[b],list[a]];save(next)}
 function menu(kind:'group'|'item',id:string,name:string,group?:string){if(!isAdmin)return null;return <DropdownMenu><DropdownMenuTrigger asChild><button className="icon-button" aria-label={'Tùy chọn '+name} disabled={busy}><MoreHorizontal size={17}/></button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={()=>kind==='group'?setForm({kind,id,name,category:project.groups.find(g=>g.id===id)?.category||'',subtitle:'',driveFolder:'',cover:''}):open(group!,all.find(i=>i.id===id)!)}>Chỉnh sửa</DropdownMenuItem><DropdownMenuItem onClick={()=>nudge(kind,id,group,-1)}><ArrowUp size={14}/> Chuyển lên</DropdownMenuItem><DropdownMenuItem onClick={()=>nudge(kind,id,group,1)}><ArrowDown size={14}/> Chuyển xuống</DropdownMenuItem>{kind==='item'&&<DropdownMenuItem onClick={()=>{const next=structuredClone(data),g=next.projects.find(p=>p.id===project.id)!.groups.find(g=>g.id===group)!,i=g.items.find(i=>i.id===id)!;g.items.splice(g.items.indexOf(i)+1,0,{...structuredClone(i),id:crypto.randomUUID(),name:i.name+' — bản sao'});save(next)}}>Nhân bản hạng mục</DropdownMenuItem>}<DropdownMenuItem className="delete-menu" onClick={()=>setDeleting({kind,id,group,name})}><Trash2 size={14}/> Xóa {kind==='group'?'nhóm':'hạng mục'}</DropdownMenuItem></DropdownMenuContent></DropdownMenu>}
 const visible=(i:Item)=>i.name.toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi'))&&(filter==='Tất cả trạng thái'||i.status===filter);const groups=project?.groups.map(g=>({...g,items:g.items.filter(visible)})).filter(g=>g.items.length||(!search&&filter==='Tất cả trạng thái'))||[];
 const {placed,categories,nextY,height}=layoutHierarchy(groups,collapsed);const rootY=height/2-86;const hierarchical=project?.groups.some(g=>g.category);const mapWidth=hierarchical?1610:1260;const offset=hierarchical?350:0;const toggle=(key:string)=>setCollapsed(prev=>prev.includes(key)?prev.filter(x=>x!==key):[...prev,key]);
 return <main className={dragging?'is-dragging':''}>
 <header className="topbar project-only-header">{token?<span className="project-title-only">{project?.name||'Dự án'}</span>:project?<DropdownMenu><DropdownMenuTrigger asChild><button className="project-title-only" title={project.name} aria-label={'Chọn hoặc quản lý dự án: '+project.name}>{project.name}</button></DropdownMenuTrigger><DropdownMenuContent align="start" className="project-title-menu">{data.projects.map(p=><DropdownMenuItem key={p.id} onClick={()=>{setProject(p.id);setSearch('');setFilter('Tất cả trạng thái')}}>{p.name}</DropdownMenuItem>)}{isAdmin&&<><DropdownMenuItem className="project-menu-settings" onClick={()=>{configure();setForm(prev=>prev?{...prev,renameOnly:true}:prev)}}>Đổi tên dự án</DropdownMenuItem><DropdownMenuItem onClick={configure}>Thông tin, ảnh bìa & Google Drive</DropdownMenuItem><DropdownMenuItem onClick={openShare}>Chia sẻ với khách</DropdownMenuItem></>}{project.driveFolder&&<DropdownMenuItem asChild><a href={project.driveFolder} target="_blank" rel="noreferrer">Mở thư mục Google Drive</a></DropdownMenuItem>}</DropdownMenuContent></DropdownMenu>:<span className="project-title-only">Dự án</span>}{!token&&isAdmin&&<button className="project-plus-only" onClick={()=>create('project')} disabled={!loaded} aria-label="Thêm dự án" title="Thêm dự án"><Plus size={22}/></button>}<div className="session-controls"><button className="theme-toggle" onClick={toggleTheme} title={theme==='dark'?'Đảo sang nền sáng':'Đảo sang nền tối'} aria-label={theme==='dark'?'Đảo sang nền sáng':'Đảo sang nền tối'}>{theme==='dark'?<><Sun size={18}/><span>Nền sáng</span></>:<><Moon size={18}/><span>Nền tối</span></>}</button>{token?null:isAdmin?<button className="login-link" onClick={logout} title="Đăng xuất quản trị"><LogOut size={17}/><span>Đăng xuất</span></button>:<button className="login-link" onClick={()=>{setLoginError('');setLoginOpen(true)}}><LogIn size={17}/><span>Đăng nhập</span></button>}</div></header>
 {error&&<div role="alert" className="error global-error">{error} {!loaded?<button onClick={load}>Thử lại</button>:retry&&!edit&&!form&&!deleting&&<button disabled={busy} onClick={()=>save(retry)}>Thử lưu lại</button>}</div>}
 {!loaded?<div className="empty"><Loader2 className="spin"/><h3>{error?'Chưa kết nối được dự án':'Đang mở không gian thiết kế…'}</h3></div>:!project?<div className="empty"><Folder size={36}/><h3>Không gian cho dự án tiếp theo</h3>{isAdmin&&<button className="primary" onClick={()=>create('project')}><Plus size={16}/> Tạo dự án</button>}{undo&&<button className="outline" onClick={async()=>{if(await save(undo,false))setUndo(null)}}><Undo2 size={16}/> Hoàn tác xóa</button>}</div>:<>
 <section className="workarea"><div className="toolbar"><Tabs value={view} onValueChange={setView}><TabsList className="view-tabs"><TabsTrigger value="map"><Network/> Sơ đồ</TabsTrigger><TabsTrigger value="table"><LayoutGrid/> Sản phẩm</TabsTrigger><TabsTrigger value="showcase"><Images/> Showcase</TabsTrigger><TabsTrigger value="report"><Presentation/> Slide tổng</TabsTrigger></TabsList></Tabs><div className="tools">{view!=='report'&&<><label className="search"><Search size={16}/><input aria-label="Tìm hạng mục" placeholder="Tìm hạng mục…" value={search} onChange={e=>setSearch(e.target.value)}/></label><Picker value={filter} onChange={setFilter} options={['Tất cả trạng thái',...statuses]}/></>}{isAdmin&&<button className="outline" onClick={()=>create('group')} disabled={busy}><Plus size={16}/> Nhóm mới</button>}{undo&&<button className="icon-button" title="Hoàn tác thao tác vừa lưu" aria-label="Hoàn tác thao tác vừa lưu" disabled={busy} onClick={async()=>{if(await save(undo,false))setUndo(null)}}><Undo2 size={17}/></button>}</div></div>
 {view==='map'&&<div className="map-outer"><div className="canvas" ref={viewport}><div style={{width:mapWidth*zoom,height:height*zoom}}><div className="map-content" style={{width:mapWidth,height,transform:`scale(${zoom})`}}><svg className="connections" width={mapWidth} height={height} aria-hidden="true">{placed.map(g=><g key={g.id}><path d={`M ${g.category?718:332} ${g.category?categories.find(c=>c.name===g.category)!.y+categories.find(c=>c.name===g.category)!.h/2:rootY+86} C ${380+offset} ${g.y+g.h/2},${380+offset} ${g.y+g.h/2},${420+offset} ${g.y+g.h/2}`}/>{!g.hidden&&g.items.map((i,j)=><path key={i.id} d={`M ${718+offset} ${g.y+g.h/2} C ${756+offset} ${g.y+g.h/2},${744+offset} ${g.y+j*86+37},${776+offset} ${g.y+j*86+37}`}/>)}</g>)}{categories.map(c=><path key={c.name} d={`M 332 ${rootY+86} C 380 ${rootY+86},380 ${c.y+c.h/2},420 ${c.y+c.h/2}`}/>)}</svg>{categories.map(c=><div key={c.name} className="group-node category-node" data-level="category" style={{top:c.y+c.h/2-44}}><button className="group-name" aria-expanded={!c.hidden} onClick={()=>toggle('category:'+c.name)}>{c.name}<small>{c.count} dòng sản phẩm {c.hidden?<ChevronRight size={13}/>:<ChevronDown size={13}/>}</small></button>{isAdmin&&<div className="node-controls"><button className="add-small" aria-label={'Thêm dòng vào '+c.name} onClick={()=>{create('group');setForm(prev=>prev?{...prev,category:c.name}:prev)}}><Plus size={16}/></button><button className="icon-button" aria-label={'Đổi tên danh mục '+c.name} onClick={()=>setForm({kind:'category',category:c.name,name:c.name,subtitle:'',driveFolder:'',cover:''})}><Settings2 size={16}/></button></div>}</div>)}{isAdmin&&<button className="new-category-on-map" style={{top:nextY-8}} onClick={()=>create('group')}><Plus size={17}/> Thêm danh mục sản phẩm</button>}<div className="root-node" style={{top:rootY}}><span className="root-code">DỰ ÁN · {all.length} HẠNG MỤC</span><button className="root-toggle" aria-label="Thu/mở dự án" aria-expanded={!collapsed.includes('root')} onClick={()=>toggle('root')}><h3>{project.name}</h3>{collapsed.includes('root')?<ChevronRight size={18}/>:<ChevronDown size={18}/>}</button><div><span>{done===all.length&&all.length?'Hoàn thành':'Đang triển khai'}</span>{isAdmin&&<button onClick={()=>create('group')} aria-label="Thêm danh mục sản phẩm" title="Thêm danh mục sản phẩm"><Plus size={19}/></button>}</div></div>
 {placed.map((g,index)=><div key={g.id}><div data-drop={JSON.stringify({kind:'group',id:g.id})} className={'group-node '+(dropTarget===g.id?'drop-target':'')} data-level="line" style={{top:g.y+g.h/2-44,left:420+offset}}>{grip({kind:'group',id:g.id})}<span className="group-number">{groupCodeOf.get(g.id)}</span><button className="group-name" aria-expanded={!g.hidden} onClick={()=>setCollapsed(collapsed.includes(g.id)?collapsed.filter(x=>x!==g.id):[...collapsed,g.id])}>{g.name}<small>{g.items.length} hạng mục {g.hidden?<ChevronRight size={13}/>:<ChevronDown size={13}/>}</small></button><div className="node-controls">{isAdmin&&<button className="add-small" onClick={()=>create('item',g.id)} aria-label={'Thêm vào '+g.name}><Plus size={16}/></button>}{isAdmin&&<button className="remove-small" disabled={busy} aria-label={'Xóa danh mục '+g.name} title="Xóa danh mục" onClick={()=>setDeleting({kind:'group',id:g.id,name:g.name})}><Minus size={16}/></button>}{menu('group',g.id,g.name)}</div></div>{!g.hidden&&<>{g.items.map((i,j)=><div key={i.id} data-drop={JSON.stringify({kind:'item',id:i.id,group:g.id})} className={'item-node '+(dropTarget===i.id?'drop-target':'')} data-level="product" style={{top:g.y+j*86,left:776+offset}}>{grip({kind:'item',id:i.id,group:g.id})}<button className="item-open" onClick={()=>open(g.id,i)}><span className="item-symbol"><Thumb file={attachments(i)[0]}/></span><span><strong>{codeOf.get(i.id)} · {i.name}</strong><Badge status={i.status}/></span><span className="item-count">{attachments(i).length||''}</span></button>{isAdmin&&<button className="remove-small" disabled={busy} aria-label={'Xóa sản phẩm '+i.name} title="Xóa sản phẩm" onClick={()=>setDeleting({kind:'item',id:i.id,group:g.id,name:i.name})}><Minus size={16}/></button>}{menu('item',i.id,i.name,g.id)}</div>)}{isAdmin&&<button className="quick-add" style={{top:g.y+g.items.length*86,left:776+offset}} onClick={()=>create('item',g.id)}><Plus size={14}/> Thêm sản phẩm / hạng mục</button>}</>}</div>)}
 </div></div></div><div className="map-footer"><span>{isAdmin?'Cuộn / chụm 2 ngón để zoom · Kéo nền để pan · Kéo ⋮⋮ để sắp xếp':'Cuộn / chụm 2 ngón để zoom · Kéo nền để di chuyển'}</span><div><button aria-label="Thu nhỏ" onClick={zoomOut}><Minus size={16}/></button><span>{Math.round(zoom*100)}%</span><button aria-label="Phóng to" onClick={zoomIn}><Plus size={16}/></button><button aria-label="Vừa màn hình" onClick={fit}><Maximize size={16}/></button></div></div></div>}
 {view==='table'&&<div className="table-wrap">{groups.map(g=><div key={g.id} className={'table-group '+(dropTarget===g.id?'drop-target':'')} data-drop={JSON.stringify({kind:'group',id:g.id})}><div className="table-group-head">{grip({kind:'group',id:g.id})}<h3>{groupCodeOf.get(g.id)} · {groupLabel(g)}</h3><span>{g.items.length}</span>{isAdmin&&<button className="outline" onClick={()=>create('item',g.id)}><Plus size={14}/> Thêm hạng mục</button>}{isAdmin&&<button className="remove-small" disabled={busy} aria-label={'Xóa danh mục '+g.name} title="Xóa danh mục" onClick={()=>setDeleting({kind:'group',id:g.id,name:g.name})}><Minus size={16}/></button>}{menu('group',g.id,g.name)}</div><Table><TableHeader><TableRow><TableHead/><TableHead>Hạng mục thiết kế</TableHead><TableHead>Trạng thái</TableHead><TableHead>Tệp thiết kế</TableHead><TableHead/></TableRow></TableHeader><TableBody>{g.items.map(i=><TableRow key={i.id} className={dropTarget===i.id?'drop-target':''} data-drop={JSON.stringify({kind:'item',id:i.id,group:g.id})}><TableCell>{grip({kind:'item',id:i.id,group:g.id})}</TableCell><TableCell><button className="table-name" onClick={()=>open(g.id,i)}>{codeOf.get(i.id)} · {i.name}</button></TableCell><TableCell>{!isAdmin?<Badge status={i.status}/>:<Picker value={i.status} options={statuses} disabled={busy} onChange={status=>{const next=structuredClone(data);next.projects.find(p=>p.id===project.id)!.groups.find(x=>x.id===g.id)!.items.find(x=>x.id===i.id)!.status=status;save(next)}}/>}</TableCell><TableCell><button onClick={()=>open(g.id,i)}>{attachments(i).length} tệp</button></TableCell><TableCell>{isAdmin&&<button className="remove-small" disabled={busy} aria-label={'Xóa sản phẩm '+i.name} title="Xóa sản phẩm" onClick={()=>setDeleting({kind:'item',id:i.id,group:g.id,name:i.name})}><Minus size={16}/></button>}{menu('item',i.id,i.name,g.id)}</TableCell></TableRow>)}</TableBody></Table>{!g.items.length&&<p className="group-empty">{isAdmin?'Thả hạng mục vào nhóm này hoặc bấm Thêm hạng mục.':'Nhóm này chưa có hạng mục.'}</p>}</div>)}{!groups.length&&<div className="empty">Không có hạng mục phù hợp.</div>}</div>}
 {view==='showcase'&&<Showcase key={project.id} groups={groups} onItem={open} onEmpty={()=>setView('table')}/>}
 {view==='report'&&<Report key={project.id} project={project} onOpen={openFile}/>}
 <div className="legend">{statuses.map(s=><Badge key={s} status={s}/>)}<span className="saved">{busy?'Đang lưu…':retry?'Có thay đổi chưa lưu':'Đã đồng bộ dự án'}</span></div></section></>}

 <Sheet open={!!edit} onOpenChange={v=>{if(!v&&!busy&&!uploading)closeEdit()}}><SheetContent className="detail-panel"><SheetHeader><div className="eyebrow">CHI TIẾT HẠNG MỤC</div><SheetTitle>{edit?`${codeOf.get(edit.item.id)} · ${edit.item.name}`:''}</SheetTitle><SheetDescription>{project?.name}</SheetDescription></SheetHeader>{edit&&(isAdmin?<div className="detail-body"><label>Tên hạng mục<input value={edit.item.name} onChange={e=>patchEdit({name:e.target.value})} maxLength={200}/></label><div className="field-row"><label>Trạng thái<Picker value={edit.item.status} options={statuses} onChange={status=>patchEdit({status})}/></label><label>Nhóm thiết kế<Picker value={edit.group} options={project.groups.map(g=>({value:g.id,label:groupLabel(g)}))} onChange={changeGroup}/></label></div><label>Ghi chú & yêu cầu thiết kế<textarea rows={3} placeholder="Ý tưởng, nội dung, yêu cầu chỉnh sửa…" value={edit.item.note} onChange={e=>patchEdit({note:e.target.value})}/></label><label>Thư mục / tệp Google Drive của hạng mục<input type="url" placeholder="https://drive.google.com/…" value={edit.item.driveUrl||''} onChange={e=>patchEdit({driveUrl:e.target.value})}/>{!driveValid(edit.item.driveUrl||'')&&<span className="field-error">Dùng liên kết HTTPS từ drive.google.com hoặc docs.google.com.</span>}</label>{edit.item.driveUrl&&driveValid(edit.item.driveUrl)&&<a className="original-file-button" href={edit.item.driveUrl} target="_blank" rel="noopener noreferrer" title="Mở file gốc trên Google Drive trong tab mới"><Download size={18}/> TẢI FILE GỐC</a>}
 <div className="section-label">Showcase & tài liệu <span>{attachments(edit.item).length}/20 tệp</span></div><div className="upload-grid">{attachments(edit.item).map(f=><div key={f.id}><button className="file-tile" onClick={event=>openItemFile(f,event.currentTarget)}><Thumb file={f}/><span>{f.name}</span>{f.type!=='image'&&<small>{f.type==='pdf'?'Xem PDF':'Google Drive'}</small>}</button><button className="remove-image" aria-label={'Bỏ '+f.name} onClick={()=>removeFile(f)}><X size={14}/></button></div>)}</div>
 <label className="upload" onDragOver={e=>{e.preventDefault();e.currentTarget.classList.add('over')}} onDragLeave={e=>e.currentTarget.classList.remove('over')} onDrop={e=>{e.preventDefault();e.currentTarget.classList.remove('over');if(!uploading&&!busy)uploadFiles(e.dataTransfer.files)}}><Upload size={25}/><strong>{uploading?'Đang tải tệp…':'Kéo thả ảnh, PDF vào đây'}</strong><span>hoặc bấm để chọn · Tối đa 20 tệp · 50 MB/tệp</span><input type="file" accept="image/jpeg,image/png,image/webp,image/gif,application/pdf" multiple disabled={uploading||busy} onChange={e=>{if(e.target.files)uploadFiles(e.target.files);e.target.value=''}}/></label>
 <details className="drive-attachment"><summary><Link2 size={15}/> Thêm tệp bằng liên kết Google Drive</summary><input placeholder="Tên tệp" aria-label="Tên tệp Drive" value={linkName} onChange={e=>setLinkName(e.target.value)}/><input type="url" placeholder="https://drive.google.com/file/d/…" aria-label="Liên kết Drive" value={linkUrl} onChange={e=>setLinkUrl(e.target.value)}/><button className="outline" disabled={!linkUrl.trim()||!driveValid(linkUrl.trim())} onClick={addLink}><Plus size={15}/> Thêm liên kết</button><p className="hint">Liên kết mở theo quyền chia sẻ hiện có trên Google Drive. Tệp tải lên website chưa tự đồng bộ sang Drive.</p></details>
 {error&&<p role="alert" className="error">{error}</p>}<div className="detail-actions"><button className="danger" onClick={()=>setDeleting({kind:'item',id:edit.item.id,group:edit.originalGroup,name:edit.item.name})}><Trash2 size={16}/> Xóa</button><button className="primary" disabled={busy||uploading} onClick={closeEdit}><Check size={16}/> Đóng</button></div><p className="hint">{savingEdit||uploading?'Đang tự lưu…':error?'Lỗi khi lưu — thử lại sau.':'Tự động lưu khi nhập.'}</p></div>:<div className="detail-body read-only-detail"><Badge status={edit.item.status}/><h3>Ghi chú & yêu cầu thiết kế</h3><p className="viewer-note">{edit.item.note||'Chưa có ghi chú.'}</p>{edit.item.driveUrl&&driveValid(edit.item.driveUrl)&&<a className="original-file-button" href={edit.item.driveUrl} target="_blank" rel="noopener noreferrer" title="Mở file gốc trên Google Drive trong tab mới"><Download size={18}/> TẢI FILE GỐC</a>}<div className="section-label">Thiết kế & tài liệu</div><div className="upload-grid">{attachments(edit.item).map(f=><button key={f.id} className="file-tile" onClick={event=>openItemFile(f,event.currentTarget)}><Thumb file={f}/><span>{f.name}</span></button>)}</div>{!attachments(edit.item).length&&<p>Chưa có tệp đính kèm.</p>}<p className="hint">Bạn đang xem dự án ở chế độ chỉ đọc.</p></div>)}</SheetContent></Sheet>
 <Dialog open={!!form} onOpenChange={v=>{if(!v&&!busy&&!uploading)setForm(null)}}><DialogContent className="project-dialog"><DialogHeader><DialogTitle>{form?.renameOnly?'Đổi tên':form?.id?'Chỉnh sửa':'Thêm'} {form?.kind==='project'?'dự án':form?.kind==='category'?'danh mục':form?.kind==='group'?'dòng sản phẩm / nhóm':'hạng mục'}</DialogTitle><DialogDescription>{form?.kind==='project'?'Thông tin dự án, bìa báo cáo và Google Drive.':project?.name}</DialogDescription></DialogHeader>{form&&<form onSubmit={e=>{e.preventDefault();submitForm()}}><label>Tên<input autoFocus required maxLength={200} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>{form.kind==='group'&&<label>Danh mục sản phẩm (để trống cho dự án 3 cấp)<input list="category-options" maxLength={200} value={form.category||''} onChange={e=>setForm({...form,category:e.target.value})}/><datalist id="category-options">{[...new Set(project.groups.map(g=>g.category).filter(Boolean))].map(c=><option key={c} value={c}/>)}</datalist><span className="hint">Tên phía trên là dòng sản phẩm. Chọn hoặc nhập danh mục để chuyển dòng vào đúng nhánh.</span></label>}{form.kind==='project'&&!form.renameOnly&&<><label>Mô tả / thông điệp<input value={form.subtitle} onChange={e=>setForm({...form,subtitle:e.target.value})}/></label><label>Thư mục Google Drive tổng<input type="url" placeholder="Có thể bổ sung sau" value={form.driveFolder} onChange={e=>setForm({...form,driveFolder:e.target.value})}/>{!driveValid(form.driveFolder)&&<span className="field-error">Liên kết Google Drive chưa hợp lệ.</span>}</label><label>Ảnh bìa báo cáo{form.cover&&<div className="cover-edit"><img src={form.cover} alt="Ảnh bìa"/><button type="button" className="outline" onClick={()=>setForm({...form,cover:''})}>Bỏ ảnh</button></div>}<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" disabled={uploading} onChange={e=>{if(e.target.files)uploadFiles(e.target.files,true)}}/></label></>}{error&&<p className="error">{error}</p>}<button className="primary form-submit" disabled={busy||uploading||!form.name.trim()||!driveValid(form.driveFolder)}><Check size={16}/> {busy||uploading?'Đang xử lý…':'Lưu'}</button>{form.kind==='project'&&form.id&&!form.renameOnly&&<button type="button" className="danger delete-project" onClick={()=>{setDeleting({kind:'project',id:form.id!,name:form.name});setForm(null)}}><Trash2 size={15}/> Xóa dự án</button>}</form>}</DialogContent></Dialog>
 <AlertDialog open={!!deleting} onOpenChange={v=>!v&&!busy&&setDeleting(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Xóa “{deleting?.name}”?</AlertDialogTitle><AlertDialogDescription>{deleting?.kind==='project'?'Toàn bộ nhóm và hạng mục trong dự án sẽ được xóa.':deleting?.kind==='group'?'Các hạng mục trong nhóm này cũng sẽ được xóa.':'Hạng mục sẽ được xóa khỏi dự án.'} Bạn có thể hoàn tác ngay sau khi xóa. Tệp gốc trên Google Drive không bị thay đổi.</AlertDialogDescription></AlertDialogHeader>{error&&<p className="error">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>Giữ lại</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();remove()}}>Xóa</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <Dialog open={loginOpen} onOpenChange={v=>{if(!loginBusy){setLoginOpen(v);if(!v)setPassword('')}}}><DialogContent className="login-dialog"><DialogHeader><DialogTitle>Đăng nhập quản trị</DialogTitle><DialogDescription>Quản lý danh mục, sản phẩm và nội dung dự án.</DialogDescription></DialogHeader><form onSubmit={login}><label htmlFor="admin-user">Tên đăng nhập<input id="admin-user" autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required autoFocus/></label><label htmlFor="admin-pass">Mật khẩu<input id="admin-pass" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{loginError&&<p className="error" role="alert">{loginError}</p>}<button className="primary form-submit" disabled={loginBusy}>{loginBusy?'Đang đăng nhập…':'Đăng nhập'}</button></form></DialogContent></Dialog>
 {itemPresentation&&<ShowcaseSlideshow {...itemPresentation} enhanced onClose={()=>setItemPresentation(null)}/>}
 <Dialog open={!!preview} onOpenChange={v=>!v&&setPreview(null)}><DialogContent className="lightbox"><DialogTitle>{preview?.name}</DialogTitle><DialogDescription>{preview?.type==='pdf'?'Xem tài liệu PDF':'Xem ảnh thiết kế'}</DialogDescription>{preview?.type==='pdf'?<><iframe src={preview.url+'#toolbar=1&navpanes=0'} title={preview.name}/><a className="text-link" href={preview.url} target="_blank" rel="noreferrer">Mở PDF trong tab mới / tải xuống <ExternalLink size={14}/></a></>:preview&&<img src={preview.url} alt={preview.name}/>}</DialogContent></Dialog>
 <Dialog open={shareOpen} onOpenChange={setShareOpen}><DialogContent className="project-dialog"><DialogHeader><DialogTitle>Chia sẻ dự án với khách</DialogTitle><DialogDescription>Khách mở liên kết chỉ thấy dự án “{project?.name}”, không thấy dự án khác. Nội dung ở chế độ chỉ đọc.</DialogDescription></DialogHeader><label>Liên kết chia sẻ<input readOnly value={shareUrl()} onFocus={e=>e.currentTarget.select()}/></label><div className="detail-actions"><button className="primary" onClick={copyShare}>{copied?'Đã sao chép':'Sao chép liên kết'}</button><button className="danger" onClick={unshare} disabled={busy}>Tắt chia sẻ</button></div><p className="hint">Tắt chia sẻ sẽ khiến liên kết hiện tại ngừng hoạt động.</p></DialogContent></Dialog>
 </main>
}
