'use client';
import {useEffect,useState,useRef} from 'react';
import {Sun,Moon,LogIn,LogOut,Search,Plus,Network,LayoutGrid,Images,ArrowUpRight,Minus,Maximize,ChevronRight,ChevronDown,Upload,Trash2,Check,Loader2,Folder,GripVertical,MoreHorizontal,ArrowUp,ArrowDown,Undo2,FileText,ExternalLink,Presentation,Settings2,Link2,X} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {DropdownMenu,DropdownMenuContent,DropdownMenuItem,DropdownMenuTrigger} from '@/components/ui/dropdown-menu';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Progress} from '@/components/ui/progress';
import {Data,Item,Project,Attachment,DragNode,initial,statuses,attachments,moveNode,driveValid} from './model';
import Report from './report';
import {useMapNavigation} from './use-map-navigation';
function Picker({value,onChange,options,disabled=false}:{value:string;onChange:(v:string)=>void;options:(string|{value:string;label:string})[];disabled?:boolean}){return <Select value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger className="picker"><SelectValue/></SelectTrigger><SelectContent>{options.map(s=>typeof s==='string'?<SelectItem key={s} value={s}>{statuses.includes(s)?<Badge status={s}/>:s}</SelectItem>:<SelectItem key={s.value} value={s.value}>{s.label}</SelectItem>)}</SelectContent></Select>}
function Badge({status}:{status:string}){return <span className={'status s'+statuses.indexOf(status)}><i/>{status}</span>}
function Thumb({file}:{file?:Attachment}){return file?.type==='image'?<img src={file.url} alt=""/>:file?.type==='pdf'?<FileText size={21}/>:file?.type==='drive'?<Link2 size={21}/>:<Images size={19}/>}
type FormState={renameOnly?:boolean;kind:'project'|'group'|'item';id?:string;group?:string;name:string;subtitle:string;driveFolder:string;cover:string};
export default function Workspace({isAdmin}:{isAdmin:boolean}){
 const [loginOpen,setLoginOpen]=useState(false),[loginBusy,setLoginBusy]=useState(false),[loginError,setLoginError]=useState(''),[username,setUsername]=useState('admin'),[password,setPassword]=useState('');
 async function login(e:React.FormEvent){e.preventDefault();setLoginBusy(true);setLoginError('');try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});const j=await r.json();if(!r.ok)throw Error(j.error);setPassword('');window.location.assign('/');}catch(e){setLoginError((e as Error).message)}finally{setLoginBusy(false)}}
 async function logout(){try{const r=await fetch('/api/auth/logout',{method:'POST'});if(!r.ok)throw Error();window.location.assign('/');}catch{setError('Chưa đăng xuất được. Vui lòng thử lại.')}}
 const [theme,setTheme]=useState('dark');useEffect(()=>{setTheme(document.documentElement.dataset.theme||'dark')},[]);function toggleTheme(){const next=theme==='dark'?'light':'dark';setTheme(next);document.documentElement.dataset.theme=next;try{localStorage.setItem('design-theme',next)}catch{}}
 const [data,setData]=useState<Data>(initial),[revision,setRevision]=useState(0),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[projectId,setProject]=useState('khesanh'),[view,setView]=useState('map'),[search,setSearch]=useState(''),[filter,setFilter]=useState('Tất cả trạng thái'),[collapsed,setCollapsed]=useState<string[]>([]);
 const [edit,setEdit]=useState<{group:string;originalGroup:string;item:Item}|null>(null),[form,setForm]=useState<FormState|null>(null),[deleting,setDeleting]=useState<{kind:'project'|'group'|'item';id:string;group?:string;name:string}|null>(null),[uploading,setUploading]=useState(false),[preview,setPreview]=useState<Attachment|null>(null),[undo,setUndo]=useState<Data|null>(null),[retry,setRetry]=useState<Data|null>(null),[dropTarget,setDropTarget]=useState(''),[dragging,setDragging]=useState(false),[linkName,setLinkName]=useState(''),[linkUrl,setLinkUrl]=useState('');
 const {viewport,zoom,zoomIn,zoomOut,fit}=useMapNavigation(view==='map'&&loaded&&data.projects.length>0);const lock=useRef(false),drag=useRef<DragNode|null>(null);
 const project=data.projects.find(p=>p.id===projectId)||data.projects[0];const all=project?.groups.flatMap(g=>g.items)||[];const done=all.filter(i=>i.status==='Hoàn thành').length;
 async function load(){setError('');try{const r=await fetch('/api/workspace');const j=await r.json();if(!r.ok)throw Error(j.error);setData(j.data);setRevision(j.revision);setLoaded(true);}catch(e){setError((e as Error).message)}}
 useEffect(()=>{load()},[]);
 async function save(next:Data,remember=true){if(!isAdmin||lock.current||!loaded)return false;lock.current=true;setBusy(true);setError('');try{const r=await fetch('/api/workspace',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:next,revision})});const j=await r.json();if(!r.ok)throw Error(j.error);if(remember)setUndo(data);setData(next);setRevision(j.revision);setRetry(null);return true;}catch(e){setError((e as Error).message);setRetry(next);return false;}finally{lock.current=false;setBusy(false)}}
 function create(kind:FormState['kind'],group?:string){if(!isAdmin)return;setError('');setForm({kind,group,name:'',subtitle:'',driveFolder:'',cover:''})}
 function configure(){if(!isAdmin)return;setError('');setForm({kind:'project',id:project.id,name:project.name,subtitle:project.subtitle,driveFolder:project.driveFolder||'',cover:project.cover||''})}
 async function submitForm(){if(!form?.name.trim()||!driveValid(form.driveFolder))return;const next=structuredClone(data),p=next.projects.find(p=>p.id===project?.id);const id=form.id||crypto.randomUUID();if(form.kind==='project'){const fields={name:form.name.trim(),subtitle:form.subtitle||'Dự án thiết kế',driveFolder:form.driveFolder,cover:form.cover};if(form.id)Object.assign(next.projects.find(p=>p.id===form.id)!,fields);else next.projects.push({id,...fields,groups:[]});}else if(form.kind==='group'){if(form.id)p!.groups.find(g=>g.id===form.id)!.name=form.name.trim();else p!.groups.push({id,name:form.name.trim(),items:[]});}else p!.groups.find(g=>g.id===form.group)!.items.push({id,name:form.name.trim(),status:statuses[0],note:'',images:[]});if(await save(next)){if(form.kind==='project')setProject(id);setForm(null)}}
 function open(group:string,item:Item){setError('');setLinkName('');setLinkUrl('');setEdit({group,originalGroup:group,item:structuredClone(item)})}
 async function saveItem(){if(!edit||!edit.item.name.trim()||!driveValid(edit.item.driveUrl||''))return;const next=structuredClone(data),p=next.projects.find(p=>p.id===project.id)!,src=p.groups.find(g=>g.id===edit.originalGroup)!;if(edit.group===edit.originalGroup)src.items=src.items.map(i=>i.id===edit.item.id?edit.item:i);else{src.items=src.items.filter(i=>i.id!==edit.item.id);p.groups.find(g=>g.id===edit.group)!.items.push(edit.item)}if(await save(next))setEdit(null)}
 async function remove(){if(!deleting)return;const next=structuredClone(data),p=next.projects.find(p=>p.id===project?.id);if(deleting.kind==='project')next.projects=next.projects.filter(p=>p.id!==deleting.id);if(deleting.kind==='group')p!.groups=p!.groups.filter(g=>g.id!==deleting.id);if(deleting.kind==='item'){const g=p!.groups.find(g=>g.id===deleting.group)!;g.items=g.items.filter(i=>i.id!==deleting.id)}if(await save(next)){setDeleting(null);setEdit(null)}}
 async function uploadFiles(files:FileList|File[],cover=false){if(!files.length)return;setUploading(true);setError('');const added:Attachment[]=[];try{for(const file of Array.from(files)){if(cover&&!file.type.startsWith('image/'))throw Error('Bìa dự án cần là tệp ảnh.');const body=new FormData();body.append('file',file);const r=await fetch('/api/upload',{method:'POST',body});const j=await r.json();if(!r.ok)throw Error(j.error);added.push(j)}}catch(e){setError((e as Error).message)}finally{if(cover&&added.length)setForm(prev=>prev?{...prev,cover:added[0].url}:prev);else if(added.length)setEdit(prev=>prev?{...prev,item:{...prev.item,files:[...(prev.item.files||[]),...added]}}:prev);setUploading(false)}}
 function openFile(f:Attachment){if(f.type==='drive'){if(driveValid(f.url))window.open(f.url,'_blank','noopener,noreferrer')}else setPreview(f)}
 function removeFile(f:Attachment){setEdit(prev=>prev?{...prev,item:{...prev.item,images:prev.item.images.filter(x=>x!==f.url),files:(prev.item.files||[]).filter(x=>x.id!==f.id)}}:prev)}
 function addLink(){if(!edit||!linkUrl.trim()||!driveValid(linkUrl.trim()))return;setEdit({...edit,item:{...edit.item,files:[...(edit.item.files||[]),{id:crypto.randomUUID(),name:linkName.trim()||'Tệp Google Drive',url:linkUrl.trim(),type:'drive'}]}});setLinkName('');setLinkUrl('')}
 function targetAt(x:number,y:number){const el=document.elementFromPoint(x,y)?.closest('[data-drop]') as HTMLElement|null;try{return el?.dataset.drop?JSON.parse(el.dataset.drop) as DragNode:null}catch{return null}}
 function grip(node:DragNode){if(!isAdmin)return null;return <button className="grip" disabled={busy} aria-label="Kéo để sắp xếp; dùng menu để di chuyển bằng bàn phím" onPointerDown={e=>{e.stopPropagation();drag.current=node;setDragging(true);e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(!drag.current)return;e.stopPropagation();const t=targetAt(e.clientX,e.clientY);setDropTarget(t?.id||'');const v=viewport.current;if(v){const r=v.getBoundingClientRect();if(e.clientY>r.bottom-50)v.scrollTop+=14;if(e.clientY<r.top+50)v.scrollTop-=14;if(e.clientX>r.right-50)v.scrollLeft+=14;if(e.clientX<r.left+50)v.scrollLeft-=14}}} onPointerUp={e=>{e.stopPropagation();const from=drag.current,to=targetAt(e.clientX,e.clientY);drag.current=null;setDragging(false);setDropTarget('');if(from&&to){const next=moveNode(data,project.id,from,to);if(next!==data)save(next)}}} onPointerCancel={()=>{drag.current=null;setDragging(false);setDropTarget('')}}><GripVertical size={16}/></button>}
 function nudge(kind:'group'|'item',id:string,group:string|undefined,delta:number){const next=structuredClone(data),p=next.projects.find(p=>p.id===project.id)!;const list=kind==='group'?p.groups:p.groups.find(g=>g.id===group)!.items;const a=list.findIndex(i=>i.id===id),b=a+delta;if(b<0||b>=list.length)return;[list[a],list[b]]=[list[b],list[a]];save(next)}
 function menu(kind:'group'|'item',id:string,name:string,group?:string){if(!isAdmin)return null;return <DropdownMenu><DropdownMenuTrigger asChild><button className="icon-button" aria-label={'Tùy chọn '+name} disabled={busy}><MoreHorizontal size={17}/></button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={()=>kind==='group'?setForm({kind,id,name,subtitle:'',driveFolder:'',cover:''}):open(group!,all.find(i=>i.id===id)!)}>Chỉnh sửa</DropdownMenuItem><DropdownMenuItem onClick={()=>nudge(kind,id,group,-1)}><ArrowUp size={14}/> Chuyển lên</DropdownMenuItem><DropdownMenuItem onClick={()=>nudge(kind,id,group,1)}><ArrowDown size={14}/> Chuyển xuống</DropdownMenuItem>{kind==='item'&&<DropdownMenuItem onClick={()=>{const next=structuredClone(data),g=next.projects.find(p=>p.id===project.id)!.groups.find(g=>g.id===group)!,i=g.items.find(i=>i.id===id)!;g.items.splice(g.items.indexOf(i)+1,0,{...structuredClone(i),id:crypto.randomUUID(),name:i.name+' — bản sao'});save(next)}}>Nhân bản hạng mục</DropdownMenuItem>}<DropdownMenuItem className="delete-menu" onClick={()=>setDeleting({kind,id,group,name})}><Trash2 size={14}/> Xóa {kind==='group'?'nhóm':'hạng mục'}</DropdownMenuItem></DropdownMenuContent></DropdownMenu>}
 const visible=(i:Item)=>i.name.toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi'))&&(filter==='Tất cả trạng thái'||i.status===filter);const groups=project?.groups.map(g=>({...g,items:g.items.filter(visible)})).filter(g=>g.items.length||(!search&&filter==='Tất cả trạng thái'))||[];
 let yy=40;const placed=groups.map(g=>{const hidden=collapsed.includes(g.id);const h=hidden?90:Math.max(90,g.items.length*86+45);const out={...g,y:yy,h,hidden};yy+=h+28;return out});const height=Math.max(580,yy+55),rootY=height/2-86;
 return <main className={dragging?'is-dragging':''}>
 <header className="topbar project-only-header">{project?<DropdownMenu><DropdownMenuTrigger asChild><button className="project-title-only" title={project.name} aria-label={'Chọn hoặc quản lý dự án: '+project.name}>{project.name}</button></DropdownMenuTrigger><DropdownMenuContent align="start" className="project-title-menu">{data.projects.map(p=><DropdownMenuItem key={p.id} onClick={()=>{setProject(p.id);setSearch('');setFilter('Tất cả trạng thái')}}>{p.name}</DropdownMenuItem>)}{isAdmin&&<><DropdownMenuItem className="project-menu-settings" onClick={()=>{configure();setForm(prev=>prev?{...prev,renameOnly:true}:prev)}}>Đổi tên dự án</DropdownMenuItem><DropdownMenuItem onClick={configure}>Thông tin, ảnh bìa & Google Drive</DropdownMenuItem></>}{project.driveFolder&&<DropdownMenuItem asChild><a href={project.driveFolder} target="_blank" rel="noreferrer">Mở thư mục Google Drive</a></DropdownMenuItem>}</DropdownMenuContent></DropdownMenu>:<span className="project-title-only">Dự án</span>}{isAdmin&&<button className="project-plus-only" onClick={()=>create('project')} disabled={!loaded} aria-label="Thêm dự án" title="Thêm dự án"><Plus size={22}/></button>}<div className="session-controls"><button className="theme-toggle" onClick={toggleTheme} title={theme==='dark'?'Bật chế độ sáng':'Bật chế độ tối'} aria-label={theme==='dark'?'Bật chế độ sáng':'Bật chế độ tối'}>{theme==='dark'?<Sun size={19}/>:<Moon size={19}/>}</button>{isAdmin?<button className="login-link" onClick={logout} title="Đăng xuất quản trị"><LogOut size={17}/><span>Đăng xuất</span></button>:<button className="login-link" onClick={()=>{setLoginError('');setLoginOpen(true)}}><LogIn size={17}/><span>Đăng nhập</span></button>}</div></header>
 {error&&<div role="alert" className="error global-error">{error} {!loaded?<button onClick={load}>Thử lại</button>:retry&&!edit&&!form&&!deleting&&<button disabled={busy} onClick={()=>save(retry)}>Thử lưu lại</button>}</div>}
 {!loaded?<div className="empty"><Loader2 className="spin"/><h3>{error?'Chưa kết nối được dự án':'Đang mở không gian thiết kế…'}</h3></div>:!project?<div className="empty"><Folder size={36}/><h3>Không gian cho dự án tiếp theo</h3>{isAdmin&&<button className="primary" onClick={()=>create('project')}><Plus size={16}/> Tạo dự án</button>}{undo&&<button className="outline" onClick={async()=>{if(await save(undo,false))setUndo(null)}}><Undo2 size={16}/> Hoàn tác xóa</button>}</div>:<>
 <section className="workarea"><div className="toolbar"><Tabs value={view} onValueChange={setView}><TabsList className="view-tabs"><TabsTrigger value="map"><Network/> Sơ đồ</TabsTrigger><TabsTrigger value="table"><LayoutGrid/> Sản phẩm</TabsTrigger><TabsTrigger value="showcase"><Images/> Showcase</TabsTrigger><TabsTrigger value="report"><Presentation/> Slide tổng</TabsTrigger></TabsList></Tabs><div className="tools">{view!=='report'&&<><label className="search"><Search size={16}/><input aria-label="Tìm hạng mục" placeholder="Tìm hạng mục…" value={search} onChange={e=>setSearch(e.target.value)}/></label><Picker value={filter} onChange={setFilter} options={['Tất cả trạng thái',...statuses]}/></>}{isAdmin&&<button className="outline" onClick={()=>create('group')} disabled={busy}><Plus size={16}/> Nhóm mới</button>}{undo&&<button className="icon-button" title="Hoàn tác thao tác vừa lưu" aria-label="Hoàn tác thao tác vừa lưu" disabled={busy} onClick={async()=>{if(await save(undo,false))setUndo(null)}}><Undo2 size={17}/></button>}</div></div>
 {view==='map'&&<div className="map-outer"><div className="canvas" ref={viewport}><div style={{width:1260*zoom,height:height*zoom}}><div className="map-content" style={{width:1260,height,transform:`scale(${zoom})`}}><svg className="connections" width="1260" height={height} aria-hidden="true">{placed.map(g=><g key={g.id}><path d={`M 332 ${rootY+86} C 380 ${rootY+86},380 ${g.y+g.h/2},420 ${g.y+g.h/2}`}/>{!g.hidden&&g.items.map((i,j)=><path key={i.id} d={`M 718 ${g.y+g.h/2} C 756 ${g.y+g.h/2},744 ${g.y+j*86+37},776 ${g.y+j*86+37}`}/>)}</g>)}</svg>{isAdmin&&<button className="new-category-on-map" style={{top:yy-8}} onClick={()=>create('group')}><Plus size={17}/> Thêm danh mục sản phẩm</button>}<div className="root-node" style={{top:rootY}}><span className="root-code">DỰ ÁN · {all.length} HẠNG MỤC</span><h3>{project.name}</h3><div><span>{done===all.length&&all.length?'Hoàn thành':'Đang triển khai'}</span>{isAdmin&&<button onClick={()=>create('group')} aria-label="Thêm danh mục sản phẩm" title="Thêm danh mục sản phẩm"><Plus size={19}/></button>}</div></div>
 {placed.map((g,index)=><div key={g.id}><div data-drop={JSON.stringify({kind:'group',id:g.id})} className={'group-node '+(dropTarget===g.id?'drop-target':'')} style={{top:g.y+g.h/2-44}}>{grip({kind:'group',id:g.id})}<span className="group-number">{String(index+1).padStart(2,'0')}</span><button className="group-name" onClick={()=>setCollapsed(collapsed.includes(g.id)?collapsed.filter(x=>x!==g.id):[...collapsed,g.id])}>{g.name}<small>{g.items.length} hạng mục {g.hidden?<ChevronRight size={13}/>:<ChevronDown size={13}/>}</small></button><div className="node-controls">{isAdmin&&<button className="add-small" onClick={()=>create('item',g.id)} aria-label={'Thêm vào '+g.name}><Plus size={16}/></button>}{isAdmin&&<button className="remove-small" disabled={busy} aria-label={'Xóa danh mục '+g.name} title="Xóa danh mục" onClick={()=>setDeleting({kind:'group',id:g.id,name:g.name})}><Minus size={16}/></button>}{menu('group',g.id,g.name)}</div></div>{!g.hidden&&<>{g.items.map((i,j)=><div key={i.id} data-drop={JSON.stringify({kind:'item',id:i.id,group:g.id})} className={'item-node '+(dropTarget===i.id?'drop-target':'')} style={{top:g.y+j*86}}>{grip({kind:'item',id:i.id,group:g.id})}<button className="item-open" onClick={()=>open(g.id,i)}><span className="item-symbol"><Thumb file={attachments(i)[0]}/></span><span><strong>{i.name}</strong><Badge status={i.status}/></span><span className="item-count">{attachments(i).length||''}</span></button>{isAdmin&&<button className="remove-small" disabled={busy} aria-label={'Xóa sản phẩm '+i.name} title="Xóa sản phẩm" onClick={()=>setDeleting({kind:'item',id:i.id,group:g.id,name:i.name})}><Minus size={16}/></button>}{menu('item',i.id,i.name,g.id)}</div>)}{isAdmin&&<button className="quick-add" style={{top:g.y+g.items.length*86}} onClick={()=>create('item',g.id)}><Plus size={14}/> Thêm sản phẩm / hạng mục</button>}</>}</div>)}
 </div></div></div><div className="map-footer"><span>{isAdmin?'Cuộn / chụm 2 ngón để zoom · Kéo nền để pan · Kéo ⋮⋮ để sắp xếp':'Cuộn / chụm 2 ngón để zoom · Kéo nền để di chuyển'}</span><div><button aria-label="Thu nhỏ" onClick={zoomOut}><Minus size={16}/></button><span>{Math.round(zoom*100)}%</span><button aria-label="Phóng to" onClick={zoomIn}><Plus size={16}/></button><button aria-label="Vừa màn hình" onClick={fit}><Maximize size={16}/></button></div></div></div>}
 {view==='table'&&<div className="table-wrap">{groups.map(g=><div key={g.id} className={'table-group '+(dropTarget===g.id?'drop-target':'')} data-drop={JSON.stringify({kind:'group',id:g.id})}><div className="table-group-head">{grip({kind:'group',id:g.id})}<h3>{g.name}</h3><span>{g.items.length}</span>{isAdmin&&<button className="outline" onClick={()=>create('item',g.id)}><Plus size={14}/> Thêm hạng mục</button>}{isAdmin&&<button className="remove-small" disabled={busy} aria-label={'Xóa danh mục '+g.name} title="Xóa danh mục" onClick={()=>setDeleting({kind:'group',id:g.id,name:g.name})}><Minus size={16}/></button>}{menu('group',g.id,g.name)}</div><Table><TableHeader><TableRow><TableHead/><TableHead>Hạng mục thiết kế</TableHead><TableHead>Trạng thái</TableHead><TableHead>Tệp thiết kế</TableHead><TableHead/></TableRow></TableHeader><TableBody>{g.items.map(i=><TableRow key={i.id} className={dropTarget===i.id?'drop-target':''} data-drop={JSON.stringify({kind:'item',id:i.id,group:g.id})}><TableCell>{grip({kind:'item',id:i.id,group:g.id})}</TableCell><TableCell><button className="table-name" onClick={()=>open(g.id,i)}>{i.name}</button></TableCell><TableCell>{!isAdmin?<Badge status={i.status}/>:<Picker value={i.status} options={statuses} disabled={busy} onChange={status=>{const next=structuredClone(data);next.projects.find(p=>p.id===project.id)!.groups.find(x=>x.id===g.id)!.items.find(x=>x.id===i.id)!.status=status;save(next)}}/>}</TableCell><TableCell><button onClick={()=>open(g.id,i)}>{attachments(i).length} tệp</button></TableCell><TableCell>{isAdmin&&<button className="remove-small" disabled={busy} aria-label={'Xóa sản phẩm '+i.name} title="Xóa sản phẩm" onClick={()=>setDeleting({kind:'item',id:i.id,group:g.id,name:i.name})}><Minus size={16}/></button>}{menu('item',i.id,i.name,g.id)}</TableCell></TableRow>)}</TableBody></Table>{!g.items.length&&<p className="group-empty">{isAdmin?'Thả hạng mục vào nhóm này hoặc bấm Thêm hạng mục.':'Nhóm này chưa có hạng mục.'}</p>}</div>)}{!groups.length&&<div className="empty">Không có hạng mục phù hợp.</div>}</div>}
 {view==='showcase'&&<div className="showcase">{groups.flatMap(g=>g.items.filter(i=>attachments(i).length).map(i=><article key={i.id} className="showcase-card"><button className="showcase-preview" onClick={()=>openFile(attachments(i)[0])}>{attachments(i)[0].type==='image'?<img src={attachments(i)[0].url} alt={i.name}/>:<div><Thumb file={attachments(i)[0]}/><strong>{attachments(i)[0].name}</strong><span>{attachments(i)[0].type==='pdf'?'Xem PDF':'Mở Google Drive'} <ArrowUpRight size={15}/></span></div>}</button><button className="showcase-description" onClick={()=>open(g.id,i)}><small>{g.name} · {attachments(i).length} tệp</small><h3>{i.name}</h3><Badge status={i.status}/></button></article>))}{!groups.some(g=>g.items.some(i=>attachments(i).length))&&<div className="empty"><Images size={38}/><h3>Showcase của dự án</h3><p>Thêm ảnh, PDF hoặc liên kết Google Drive vào từng hạng mục để trưng bày thiết kế.</p><button className="outline" onClick={()=>setView('table')}>Chọn hạng mục <ArrowUpRight size={16}/></button></div>}</div>}
 {view==='report'&&<Report project={project} onOpen={openFile}/>}
 <div className="legend">{statuses.map(s=><Badge key={s} status={s}/>)}<span className="saved">{busy?'Đang lưu…':retry?'Có thay đổi chưa lưu':'Đã đồng bộ dự án'}</span></div></section></>}

 <Sheet open={!!edit} onOpenChange={v=>{if(!v&&!busy&&!uploading)setEdit(null)}}><SheetContent className="detail-panel"><SheetHeader><div className="eyebrow">CHI TIẾT HẠNG MỤC</div><SheetTitle>{edit?.item.name}</SheetTitle><SheetDescription>{project?.name}</SheetDescription></SheetHeader>{edit&&(isAdmin?<div className="detail-body"><label>Tên hạng mục<input value={edit.item.name} onChange={e=>setEdit({...edit,item:{...edit.item,name:e.target.value}})} maxLength={200}/></label><div className="field-row"><label>Trạng thái<Picker value={edit.item.status} options={statuses} onChange={status=>setEdit({...edit,item:{...edit.item,status}})}/></label><label>Nhóm thiết kế<Picker value={edit.group} options={project.groups.map(g=>({value:g.id,label:g.name}))} onChange={group=>setEdit({...edit,group})}/></label></div><label>Ghi chú & yêu cầu thiết kế<textarea rows={3} placeholder="Ý tưởng, nội dung, yêu cầu chỉnh sửa…" value={edit.item.note} onChange={e=>setEdit({...edit,item:{...edit.item,note:e.target.value}})}/></label><label>Thư mục / tệp Google Drive của hạng mục<input type="url" placeholder="https://drive.google.com/…" value={edit.item.driveUrl||''} onChange={e=>setEdit({...edit,item:{...edit.item,driveUrl:e.target.value}})}/>{!driveValid(edit.item.driveUrl||'')&&<span className="field-error">Dùng liên kết HTTPS từ drive.google.com hoặc docs.google.com.</span>}</label>{edit.item.driveUrl&&driveValid(edit.item.driveUrl)&&<a className="text-link" href={edit.item.driveUrl} target="_blank" rel="noreferrer">Mở trên Google Drive <ExternalLink size={14}/></a>}
 <div className="section-label">Showcase & tài liệu <span>{attachments(edit.item).length} tệp</span></div><div className="upload-grid">{attachments(edit.item).map(f=><div key={f.id}><button className="file-tile" onClick={()=>openFile(f)}><Thumb file={f}/><span>{f.name}</span>{f.type!=='image'&&<small>{f.type==='pdf'?'Xem PDF':'Google Drive'}</small>}</button><button className="remove-image" aria-label={'Bỏ '+f.name} onClick={()=>removeFile(f)}><X size={14}/></button></div>)}</div>
 <label className="upload" onDragOver={e=>{e.preventDefault();e.currentTarget.classList.add('over')}} onDragLeave={e=>e.currentTarget.classList.remove('over')} onDrop={e=>{e.preventDefault();e.currentTarget.classList.remove('over');if(!uploading&&!busy)uploadFiles(e.dataTransfer.files)}}><Upload size={25}/><strong>{uploading?'Đang tải tệp…':'Kéo thả ảnh, PDF vào đây'}</strong><span>hoặc bấm để chọn · Tối đa 25 MB / tệp</span><input type="file" accept="image/jpeg,image/png,image/webp,image/gif,application/pdf" multiple disabled={uploading||busy} onChange={e=>{if(e.target.files)uploadFiles(e.target.files);e.target.value=''}}/></label>
 <details className="drive-attachment"><summary><Link2 size={15}/> Thêm tệp bằng liên kết Google Drive</summary><input placeholder="Tên tệp" aria-label="Tên tệp Drive" value={linkName} onChange={e=>setLinkName(e.target.value)}/><input type="url" placeholder="https://drive.google.com/file/d/…" aria-label="Liên kết Drive" value={linkUrl} onChange={e=>setLinkUrl(e.target.value)}/><button className="outline" disabled={!linkUrl.trim()||!driveValid(linkUrl.trim())} onClick={addLink}><Plus size={15}/> Thêm liên kết</button><p className="hint">Liên kết mở theo quyền chia sẻ hiện có trên Google Drive. Tệp tải lên website chưa tự đồng bộ sang Drive.</p></details>
 {error&&<p role="alert" className="error">{error}</p>}<div className="detail-actions"><button className="danger" onClick={()=>setDeleting({kind:'item',id:edit.item.id,group:edit.originalGroup,name:edit.item.name})}><Trash2 size={16}/> Xóa</button><button className="primary" disabled={busy||uploading||!edit.item.name.trim()||!driveValid(edit.item.driveUrl||'')} onClick={saveItem}><Check size={16}/> {busy?'Đang lưu…':'Lưu thay đổi'}</button></div><p className="hint">Bấm Lưu thay đổi để cập nhật tệp và nội dung vào dự án.</p></div>:<div className="detail-body read-only-detail"><Badge status={edit.item.status}/><h3>Ghi chú & yêu cầu thiết kế</h3><p className="viewer-note">{edit.item.note||'Chưa có ghi chú.'}</p>{edit.item.driveUrl&&driveValid(edit.item.driveUrl)&&<a className="text-link" href={edit.item.driveUrl} target="_blank" rel="noreferrer">Mở Google Drive <ExternalLink size={14}/></a>}<div className="section-label">Thiết kế & tài liệu</div><div className="upload-grid">{attachments(edit.item).map(f=><button key={f.id} className="file-tile" onClick={()=>openFile(f)}><Thumb file={f}/><span>{f.name}</span></button>)}</div>{!attachments(edit.item).length&&<p>Chưa có tệp đính kèm.</p>}<p className="hint">Bạn đang xem dự án ở chế độ chỉ đọc.</p></div>)}</SheetContent></Sheet>
 <Dialog open={!!form} onOpenChange={v=>{if(!v&&!busy&&!uploading)setForm(null)}}><DialogContent className="project-dialog"><DialogHeader><DialogTitle>{form?.renameOnly?'Đổi tên':form?.id?'Chỉnh sửa':'Thêm'} {form?.kind==='project'?'dự án':form?.kind==='group'?'nhóm thiết kế':'hạng mục'}</DialogTitle><DialogDescription>{form?.kind==='project'?'Thông tin dự án, bìa báo cáo và Google Drive.':project?.name}</DialogDescription></DialogHeader>{form&&<form onSubmit={e=>{e.preventDefault();submitForm()}}><label>Tên<input autoFocus required maxLength={200} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>{form.kind==='project'&&!form.renameOnly&&<><label>Mô tả / thông điệp<input value={form.subtitle} onChange={e=>setForm({...form,subtitle:e.target.value})}/></label><label>Thư mục Google Drive tổng<input type="url" placeholder="Có thể bổ sung sau" value={form.driveFolder} onChange={e=>setForm({...form,driveFolder:e.target.value})}/>{!driveValid(form.driveFolder)&&<span className="field-error">Liên kết Google Drive chưa hợp lệ.</span>}</label><label>Ảnh bìa báo cáo{form.cover&&<div className="cover-edit"><img src={form.cover} alt="Ảnh bìa"/><button type="button" className="outline" onClick={()=>setForm({...form,cover:''})}>Bỏ ảnh</button></div>}<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" disabled={uploading} onChange={e=>{if(e.target.files)uploadFiles(e.target.files,true)}}/></label></>}{error&&<p className="error">{error}</p>}<button className="primary form-submit" disabled={busy||uploading||!form.name.trim()||!driveValid(form.driveFolder)}><Check size={16}/> {busy||uploading?'Đang xử lý…':'Lưu'}</button>{form.kind==='project'&&form.id&&!form.renameOnly&&<button type="button" className="danger delete-project" onClick={()=>{setDeleting({kind:'project',id:form.id!,name:form.name});setForm(null)}}><Trash2 size={15}/> Xóa dự án</button>}</form>}</DialogContent></Dialog>
 <AlertDialog open={!!deleting} onOpenChange={v=>!v&&!busy&&setDeleting(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Xóa “{deleting?.name}”?</AlertDialogTitle><AlertDialogDescription>{deleting?.kind==='project'?'Toàn bộ nhóm và hạng mục trong dự án sẽ được xóa.':deleting?.kind==='group'?'Các hạng mục trong nhóm này cũng sẽ được xóa.':'Hạng mục sẽ được xóa khỏi dự án.'} Bạn có thể hoàn tác ngay sau khi xóa. Tệp gốc trên Google Drive không bị thay đổi.</AlertDialogDescription></AlertDialogHeader>{error&&<p className="error">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>Giữ lại</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();remove()}}>Xóa</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <Dialog open={loginOpen} onOpenChange={v=>{if(!loginBusy){setLoginOpen(v);if(!v)setPassword('')}}}><DialogContent className="login-dialog"><DialogHeader><DialogTitle>Đăng nhập quản trị</DialogTitle><DialogDescription>Quản lý danh mục, sản phẩm và nội dung dự án.</DialogDescription></DialogHeader><form onSubmit={login}><label htmlFor="admin-user">Tên đăng nhập<input id="admin-user" autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required autoFocus/></label><label htmlFor="admin-pass">Mật khẩu<input id="admin-pass" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{loginError&&<p className="error" role="alert">{loginError}</p>}<button className="primary form-submit" disabled={loginBusy}>{loginBusy?'Đang đăng nhập…':'Đăng nhập'}</button></form></DialogContent></Dialog>
 <Dialog open={!!preview} onOpenChange={v=>!v&&setPreview(null)}><DialogContent className="lightbox"><DialogTitle>{preview?.name}</DialogTitle><DialogDescription>{preview?.type==='pdf'?'Xem tài liệu PDF':'Xem ảnh thiết kế'}</DialogDescription>{preview?.type==='pdf'?<><iframe src={preview.url+'#toolbar=1&navpanes=0'} title={preview.name}/><a className="text-link" href={preview.url} target="_blank" rel="noreferrer">Mở PDF trong tab mới / tải xuống <ExternalLink size={14}/></a></>:preview&&<img src={preview.url} alt={preview.name}/>}</DialogContent></Dialog>
 </main>
}
