"use strict";
const API="https://undefined-seeks-mall-disclose.trycloudflare.com";
const TOKEN_KEY="khanh-course-admin-session";
const state={token:sessionStorage.getItem(TOKEN_KEY)||"",dashboard:null,filter:"ALL"};
const $=selector=>document.querySelector(selector);
function make(tag,text,className=""){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(className)node.className=className;return node}
function setStatus(node,text,type=""){node.textContent=text;node.className=`status ${type}`.trim()}
async function api(path,options={}){const headers={...(options.body?{"Content-Type":"application/json"}:{}),...(state.token?{Authorization:`Bearer ${state.token}`}:{})};const response=await fetch(API+path,{...options,headers:{...headers,...options.headers}});let body={};try{body=await response.json()}catch(_){body={}}if(!response.ok){const error=new Error(body.error||"request_failed");error.status=response.status;throw error}return body}
function label(status){return {SUBMITTED:"Đang chờ chấm",NEEDS_REVISION:"Cần sửa",PASSED:"Đạt",MISSING:"Chưa nộp"}[status]||status}
function renderSummary(){const box=$("#summary-cards");box.replaceChildren();const s=state.dashboard.summary;[[s.students,"Học viên"],[s.submitted,"Chờ chấm"],[s.needs_revision,"Cần sửa"],[s.passed,"Đã đạt"]].forEach(([value,title])=>{const card=make("article",undefined,"summary-card");card.append(make("strong",String(value)),make("span",title));box.append(card)})}
function rows(){const result=[];state.dashboard.students.forEach(student=>{for(let week=1;week<=6;week++){const submission=student.progress[String(week)];result.push({student,week,submission,status:submission?.review_status||"MISSING"})}});return result.filter(row=>state.filter==="ALL"||row.status===state.filter).sort((a,b)=>{const priority={SUBMITTED:0,NEEDS_REVISION:1,MISSING:2,PASSED:3};return priority[a.status]-priority[b.status]||a.student.display_name.localeCompare(b.student.display_name)||a.week-b.week})}
function renderTable(){const tbody=$("#student-table");tbody.replaceChildren();rows().forEach(row=>{const tr=document.createElement("tr");tr.append(make("td",row.student.display_name),make("td",`Tuần ${row.week}`),make("td",row.submission?`v${row.submission.version}`:"—"));const statusCell=document.createElement("td");statusCell.append(make("span",label(row.status),`badge ${row.status.toLowerCase().replace("_","-")}`));tr.append(statusCell);const action=document.createElement("td");if(row.submission){const button=make("button","Xem và chấm");button.type="button";button.addEventListener("click",()=>selectSubmission(row));action.append(button)}else action.textContent="Chưa có bài";tr.append(action);tbody.append(tr)})}
function selectSubmission(row){const section=$("#review-section"),form=$("#review-form"),context=$("#review-context");section.hidden=false;form.elements.submission_id.value=row.submission.id;form.elements.review_status.value=row.submission.review_status;form.elements.instructor_score.value=row.submission.instructor_score??"";form.elements.instructor_feedback.value=row.submission.instructor_feedback||"";context.replaceChildren(make("strong",`${row.student.display_name} · Tuần ${row.week} · v${row.submission.version}`),make("p",row.submission.note));const link=make("a","Mở sản phẩm");link.href=row.submission.artifact_url;link.target="_blank";link.rel="noopener noreferrer";context.append(link);section.scrollIntoView({behavior:"smooth",block:"start"});form.elements.review_status.focus()}
async function loadDashboard(){state.dashboard=await api("/course/admin/dashboard");$("#admin-login-panel").hidden=true;$("#admin-app").hidden=false;renderSummary();renderTable()}
$("#admin-login").addEventListener("submit",async event=>{event.preventDefault();const form=event.currentTarget,status=$("#login-status");setStatus(status,"Đang xác thực…");try{const result=await api("/course/admin/login",{method:"POST",body:JSON.stringify({key:form.elements.admin_key.value})});state.token=result.token;sessionStorage.setItem(TOKEN_KEY,state.token);form.reset();await loadDashboard()}catch(error){setStatus(status,error.status===401?"Khóa quản trị không đúng.":"Chưa thể kết nối dashboard.","error")}});
$("#status-filter").addEventListener("change",event=>{state.filter=event.target.value;renderTable()});
$("#review-form").addEventListener("submit",async event=>{event.preventDefault();const form=event.currentTarget,status=$("#review-status");setStatus(status,"Đang lưu đánh giá…");try{await api(`/course/admin/submissions/${encodeURIComponent(form.elements.submission_id.value)}`,{method:"PATCH",body:JSON.stringify({review_status:form.elements.review_status.value,instructor_score:Number(form.elements.instructor_score.value),instructor_feedback:form.elements.instructor_feedback.value.trim()})});await loadDashboard();setStatus(status,"Đã lưu đánh giá.","success")}catch(_){setStatus(status,"Không thể lưu. Kiểm tra điểm và nhận xét.","error")}});
$("#logout").addEventListener("click",()=>{sessionStorage.removeItem(TOKEN_KEY);state.token="";location.reload()});
if(state.token)loadDashboard().catch(()=>{sessionStorage.removeItem(TOKEN_KEY);state.token=""});
